name: Run Selenium Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Install browsers & drivers
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          export CHROME_BIN=/usr/bin/chromium-browser
          export CHROMEDRIVER_PATH=/usr/bin/chromedriver

      - name: Run Selenium tests
        run: |
          python Call.py
          python Login.py
          python Sign_up.py
          python Create_Pro_Personality.py
          python Create_Quick_Personality.py
          python Side_bar_actions.py
          python Multiple_users.py
