name: Run Selenium Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Selenium Automation Tests
      run: |
        mkdir -p reports
        pytest --junitxml=reports/results.xml --disable-warnings -q

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: selenium-test-results
        path: reports/results.xml
